version: '2'
services:
 docker-registry:
  container_name: registry
  restart: always
  image: registry:2.5.1
  ports:
    - 5000:5000
    - 5001:5001
  volumes:
    #- registry_data:/var/lib/registry
    - ./integration/registry.yml:/etc/docker/registry/config.yml
  networks:
     - registry
 dim:
  container_name: dim
  restart: always
  build: .
  ports:
    - 6000:6000
  networks:
    - registry
 apache:
   container_name: apache
   restart: always
   image: rgoyard/apache-proxy
   ports:
     - 80:80
   volumes:
     - ./integration/registry.conf:/conf/proxy.conf
   networks:
       - registry
networks:
  registry:
    driver: bridge
#volumes:
#  registry_data:
#    external: false
